出力メッセージの調整
kusumotolab/kGenProg pull request #778
Opened 2020-09-01 03:06 UTC by RyokoIzuta

resolve #735 
partly resolve #738 

* 世代ごとに出すfitnessの小数を小数点第3位に四捨五入するように
    * これを実現するために `DecimalFormat` クラスのインポート
* kGP終了時に出るメッセージの順番を変更
    * これを実現するために新たな列挙型 `ExitStatus` の作成

2020-09-01 03:11 UTC, RyokoIzuta commented
#738 の残りの課題である「出力する情報を増やす」は以下の情報を格納する場所を悩んでいるためまだ実装していません
（あとミーティングに間に合わなさそうだった）
* 生成した総個体数
* Syntax valid な個体の数
* build success な個体の数

enumの追加場所など自信ないです
また、`ExitStatus`使わなくても実装できるよなどの他のアイディアがあれば教えてください

2020-09-01 08:20 UTC, hnymA requested changes
レビューしました．`Enum`を使うのは良いと思います
何点か確認と修正お願いします！

2020-09-01 08:20 UTC, hnymA commented on src/main/java/jp/kusumotolab/kgenprog/KGenProgMain.java
> +        log.info("GA stopped.");
つまり
```diff
+   log.info("GA stopped.");
    // 出力処理を行う
    exporters.exportAll(variantStore);
```

2020-09-01 08:20 UTC, hnymA commented on src/main/java/jp/kusumotolab/kgenprog/KGenProgMain.java
> +        .append("Overall")
MTGで話してたやつ
Summaryの方がいいかも

```suggestion
        .append("Summary")
```

2020-09-01 08:20 UTC, hnymA commented on src/main/java/jp/kusumotolab/kgenprog/KGenProgMain.java
> +    SUCCESS("SUCCESS"), FAIL_GEN("FAIL(maximum generation)"), FAIL_TIME("FAIL(time limit)");
- successの対義語はfailureかな？
- 定数名は中途半端に略すより，全部書き切った方が分かりやすいと思う
   - `FAILURE_GENERATION`あるいは`FAILURE_MAXIMUM_GENERATION`
   - `FAILURE_TIME`あるいは`FAILURE_TIME_LIMIT`
- めっちゃ細かいけど，括弧の前に空白あった方がいいかも

```suggestion
    SUCCESS("SUCCESS"), FAILURE_GENERATION("FAILURE (maximum generation)"), FAILURE_TIME("FAILURE (time limit)");
```

2020-09-01 13:36 UTC, RyokoIzuta commented
コメントありがとうございます！
全てその通りだと思ったので反映しました。

また、 #738 の残りの要素である「情報の追加」も実装しました。
確認お願いします。

2020-09-02 05:27 UTC, hnymA approved these changes
反映ありがとう！
追加実装についても特に言うことないです

マージします，お疲れさま！

2020-09-02 05:27 UTC, merged