SimpleMutationにおいて置換対象のプログラム要素に応じた再利用ノードの選択
kusumotolab/kGenProg pull request #784
Opened 2020-09-01 09:05 UTC by YoshikiHigo

SimpleMutationの置換操作において，置換対象のプログラム要素に応じた再利用ノードの選択処理を実装した．
具体的には，置換対象がプログラム文の場合はプログラム文のみを再利用ノードとして選択，
置換対象が式の場合は式のみを再利用ノードとして選択するようにした．

本来は，Rouletteにおいて再利用対象としないノードの重みを0にする実装が良さそう．
しかし，対象プログラム全体を対象としたRouletteはkGenProgの実行開始時に一度だけ作成され，
重みを与える関するはRouletteのコンストラクタとして与える仕様となっているため，その実装には大規模な改修が必要．
https://github.com/kusumotolab/kGenProg/blob/59944899b179f724d9e8ade768a762f30e7888b6/src/main/java/jp/kusumotolab/kgenprog/ga/mutation/selection/RouletteSelection.java#L59-L63
https://github.com/kusumotolab/kGenProg/blob/59944899b179f724d9e8ade768a762f30e7888b6/src/main/java/jp/kusumotolab/kgenprog/ga/Roulette.java#L30-L33

そのため，SimpleMutation#chooseForReuse において，再利用されたノードが適切ではない場合にもう一度再利用ノードを選択し直す，という方針で実装した．

2020-09-16 03:53 UTC, shinsuke-mat requested changes
2つコードに対する小さな修正追加しました．

あと単体テストあった方が良さそうです．
期待通り振る舞ってるかがよくわからん．

2020-09-16 03:53 UTC, shinsuke-mat commented on src/main/java/jp/kusumotolab/kgenprog/ga/mutation/SimpleMutation.java
> +    return nodeForReuse;
一時変数を使わない書き方の方がimmuneでよいと思います．
```java
    int attempt = 0;
    final boolean isStatement = location.isStatement();
    final boolean isExpression = location.isExpression();
    while (attempt++ < ATTEMPT_FOR_REPLACE) {
      final ASTNode nodeForReuse = candidateSelection.exec(query);
      if (isStatement && nodeForReuse instanceof Statement
          || isExpression && nodeForReuse instanceof Expression) {
        return nodeForReuse;
      }
    }
    return null;
```

2020-09-16 03:53 UTC, shinsuke-mat commented on src/main/java/jp/kusumotolab/kgenprog/ga/mutation/SimpleMutation.java
> +  private static final int ATTEMPT_FOR_REPLACE = 100;
`REPLACE` であってます？ `RESELECTION` では？

2020-09-28 07:28 UTC, YoshikiHigo commented
修正しました．
もう一度レビューお願いします．

2020-10-06 06:27 UTC, shinsuke-mat approved these changes

2020-10-06 06:28 UTC, shinsuke-mat commented
よさそうです．マージします．お疲れさんです．

2020-10-06 06:28 UTC, merged