Fix crossover location bug
kusumotolab/kGenProg pull request #789
Opened 2020-09-29 06:01 UTC by hrtwt

resolve #788 
候補ノード選定に木のたぐり方を追加した．

2020-10-05 03:59 UTC, shinsuke-mat requested changes

2020-10-05 03:59 UTC, shinsuke-mat commented on src/test/java/jp/kusumotolab/kgenprog/project/jdt/JDTASTCrossoverLocationTest.java
> +    assertThat(node).isEqualTo(location.getNode());
ここのassertionガバくない？
位置がずれててもテスト成功しそう．

2020-10-06 06:31 UTC, hrtwt commented on src/test/java/jp/kusumotolab/kgenprog/project/jdt/JDTASTCrossoverLocationTest.java
> +    assertThat(node).isEqualTo(location.getNode());
`isEqualTo` ではなく `isSameAs` を使うように変更しました．

2020-10-06 06:36 UTC, shinsuke-mat commented
よさそう．マージします．お疲れさん

2020-10-06 06:36 UTC, shinsuke-mat approved these changes

2020-10-06 06:37 UTC, merged