kgpMainでの異常系処理を追加
kusumotolab/kGenProg pull request #802
Opened 2020-12-01 02:25 UTC by shinsuke-mat

resolve #610
resolve #645
resolve #734
resolve #740

kGenProgMainの異常系処理を追加．
利用者目線での利便性が向上．

## やったこと
### 本質
- 100万世代問題の解決（#645 #734 最初からtest failを含まないケース）
- 0世代問題の解決（#734 #740 最初からbuild failを含むケース）
- プロジェクトルートが間違っているケースの対応
- 上記異常系3ケースのテスト追加

### 上に付随
- Main/Launcher周りの返り値をExitStatusに変更
- EmptyTestResultsからビルド失敗理由を辿れるように変更
- TargetProject#isValidの追加
- GAのメインループをメソッドとして切り出し

### その他リファクタリング系
無駄なRuntimeException宣言を削除
無駄なTestExecutor#finish #initializeを削除
Mainクラスでのログ出力周りをinner class化，さらに改善

2020-12-02 06:28 UTC, hnymA requested changes
レビューしました．細かい点をいくつかコメントしたので修正/検討お願いします．

2020-12-03 01:26 UTC, shinsuke-mat commented on example/Abnormals/BuildFailure/src/example/CloseToZeroTest.java
> +    assertEquals(-9, new CloseToZero().close_to_zero(-10));
`assertEquals` は expect, actual の順で書くのでこれで正しい．
`Assertj#assertThat` は（英語文法とassertjの仕組み上）actual, expect の順で書くので混同しがち．

2020-12-03 01:29 UTC, shinsuke-mat commented on src/main/java/jp/kusumotolab/kgenprog/project/test/EmptyTestResults.java
>    @Deprecated
agree

至った過程をメモしておく．

このクラスはsingletonにする予定，かつ別のクラスが参照していたので，tech debtのつもりで @depre にしてあった．
でもこのクラスはある失敗を表すクラスで，そもそもsingletonであるべきではない．失敗の理由を記載できなくなる．

そのためdepreするべきではない．

2020-12-03 03:23 UTC, hnymA commented on example/Abnormals/BuildFailure/src/example/CloseToZeroTest.java
> +    assertEquals(-9, new CloseToZero().close_to_zero(-10));
すいません，その通りですね
混乱してました

2020-12-03 03:24 UTC, hnymA approved these changes
ありがとうございます．良いと思います
マージしますね
お疲れ様でした

2020-12-03 03:25 UTC, merged