StopFirstを実装した
kusumotolab/kGenProg pull request #808
Opened 2020-12-03 09:58 UTC by YoshikiHigo

resolve #434 

ある世代Nにおいて，必要な数の修正プログラムを生成した場合の挙動を変更した．
旧：その世代の最後まで引き続き変異プログラムの生成とテスト実行の処理を行う
新：ただちにその世代の処理を終える

2020-12-08 00:37 UTC, shinsuke-mat requested changes
いくつか改善案です．

2020-12-08 00:37 UTC, shinsuke-mat commented on src/main/java/jp/kusumotolab/kgenprog/ga/crossover/CrossoverAdaptor.java
> +
GOTOを避けたいのでメソッドに切り出した方がよさそう
```java

    final List<Variant> variants = generateVariants(variantStore, validVariants);

    // バリアントを作りすぎた場合はそれを除いてリターン
    return generatingCount < variants.size() ? variants.subList(0, generatingCount) : variants;
  }

  private List<Variant> generateVariants(final VariantStore variantStore,
      final List<Variant> validVariants) {
    final List<Variant> generatedVariants = new ArrayList<>();
    int foundSolutions = variantStore.getFoundSolutionsNumber()
        .get();

    // generatingCountを超えるまでバリアントを作りづづける
    while (generatedVariants.size() < generatingCount) {
      try {
        generatedVariants.addAll(makeVariants(validVariants, variantStore));
        foundSolutions += generatedVariants.stream()
            .filter(Variant::isCompleted)
            .count();
        if (requiredSolutions <= foundSolutions) {
          return generatedVariants;
        }
      } catch (final CrossoverInfeasibleException e) {
        log.debug(e.getMessage());
      }
    }
    return generatedVariants;
  }

```

厳密には元のコードと挙動は違います．
そのため `RandomCrossoverTest#testStopFirst02` が落ちます．
詳細は後述

2020-12-08 00:37 UTC, shinsuke-mat commented on src/test/java/jp/kusumotolab/kgenprog/ga/crossover/RandomCrossoverTest.java
> +    assertThat(variants).hasSize(1);
先のテストが落ちる問題の箇所です．

stopFirst=onにすると解発見時に強制的にGAを止める，という点は認識が一致してると思います．
ただ，その際に以下A/Bどちらの振る舞いをするかの認識違いがありそう．

A. 常に「発見した解の数<=期待する解の数」を満たす．
B. 常に「発見した解の数<=期待する解の数」を満たすとは限らない．

Mutationは一つずつ個体を生成するのでAのような挙動でも自然です．

一方，CrossOverは複数個体をまとめて生成します．
当然その中には解個体が複数含まれます．
その際に，せっかく見つけた（コンパイル+評価済みの）解個体を捨ててAを満たすよりは，
Bのように返した方が損がないと思います．

あくまで「stopFirstはGAのプロセスを強制停止して時間を節約する機能」であり，
Aを満たすか否かは別の問題だと思います．

2020-12-08 05:22 UTC, YoshikiHigo commented on src/test/java/jp/kusumotolab/kgenprog/ga/crossover/RandomCrossoverTest.java
> +    assertThat(variants).hasSize(1);
個体の実態はLazyVariantなので，isCompletedが呼び出されたときにテスト実行がされますよね．
Bだと交叉により生成した全ての個体に対してisCompletedが呼び出されます（テストが実行される）．
なので，stopFirstにする意義が薄れるように思いますがどうでしょうか？

2020-12-08 05:44 UTC, shinsuke-mat commented on src/test/java/jp/kusumotolab/kgenprog/ga/crossover/RandomCrossoverTest.java
> +    assertThat(variants).hasSize(1);
遅延評価を忘れてました．
100%agreeです．

以下のstream使ってさらっとやってる部分を手続き的にやるしかないですね．
とりあえず，return使えばgotoは消えると思います．

```java
    while (generatedVariants.size() < generatingCount) {
      try {
        generatedVariants.addAll(makeVariants(validVariants, variantStore));
        foundSolutions += generatedVariants.stream()
            .filter(Variant::isCompleted)
            .count();
        if (requiredSolutions <= foundSolutions) {
          return generatedVariants;
        }
      } catch (final CrossoverInfeasibleException e) {
        log.debug(e.getMessage());
      }
    }
```

2020-12-08 05:57 UTC, YoshikiHigo commented on src/test/java/jp/kusumotolab/kgenprog/ga/crossover/RandomCrossoverTest.java
> +    assertThat(variants).hasSize(1);
OKです．

2020-12-08 06:16 UTC, YoshikiHigo commented on src/test/java/jp/kusumotolab/kgenprog/ga/crossover/RandomCrossoverTest.java
> +    assertThat(variants).hasSize(1);
レビューありがとうございました．
修正したのでもう一度確認お願いします．

2020-12-08 08:58 UTC, shinsuke-mat requested changes
いいですね．
1点，lambdaの省略記法だけ修正お願いします．

2020-12-08 08:58 UTC, shinsuke-mat commented on src/test/java/jp/kusumotolab/kgenprog/ga/crossover/RandomCrossoverTest.java
> +    });
return 省略できます．
```java
    when(testVariants.variantStore.createVariant(any(), any())).then(ans ->
        new Variant(0, 0, ans.getArgument(0), null, null, new SimpleFitness(1.0), null,
            ans.getArgument(1))
    );
```

2020-12-08 08:58 UTC, shinsuke-mat commented on src/test/java/jp/kusumotolab/kgenprog/ga/crossover/SinglePointCrossoverTest.java
> +    });
return

2020-12-08 08:58 UTC, shinsuke-mat commented on src/test/java/jp/kusumotolab/kgenprog/ga/crossover/UniformCrossoverTest.java
> +    });
return

2020-12-08 08:58 UTC, shinsuke-mat commented on src/test/java/jp/kusumotolab/kgenprog/ga/mutation/SimpleMutationTest.java
> +    });
return

2020-12-08 08:58 UTC, shinsuke-mat commented on src/test/java/jp/kusumotolab/kgenprog/ga/crossover/CascadeCrossoverTest.java
> +    });
return

2020-12-08 14:44 UTC, YoshikiHigo commented
修正しましたので，再度確認お願いします．

2020-12-09 00:52 UTC, shinsuke-mat approved these changes
よさそう．
お疲れさんです．マージします．

2020-12-09 00:52 UTC, merged