テスト実行時間のログ出力機能を追加
kusumotolab/kGenProg pull request #812
Opened 2020-12-07 05:16 UTC by raedion

kGPの各世代におけるテスト実行に要する時間を計測し、その結果を出力する機能を追加しました。

2020-12-07 08:44 UTC, shinsuke-mat commented
PRの際は必ず `resolve #issueid` を明記してください．

2020-12-07 09:48 UTC, ty-v1 commented
レビューしました

出力する情報は，マージした後に議論しましょう

2020-12-07 10:04 UTC, ty-v1 requested changes
フォーマットがおかしいので，[ここ](https://github.com/kusumotolab/kGenProg/blob/master/doc/CONTRIBUTING.md)を参考にして設定してください

2020-12-07 10:04 UTC, ty-v1 commented
レビューしました

出力する情報は，マージした後に議論しましょう

2020-12-10 13:11 UTC, ty-v1 requested changes
レビューしました

2020-12-10 13:11 UTC, ty-v1 commented on src/main/java/jp/kusumotolab/kgenprog/project/test/TestThread.java
> +    stopWatch.start();
上の2行の処理は，`StopWatch.createStarted()`を使えば1行でかけます

2020-12-10 13:11 UTC, ty-v1 commented on src/main/java/jp/kusumotolab/kgenprog/project/test/TestResults.java
> +  public TestResults(final BuildResults buildResults, final StopWatch stopWatch) {
setterを使っている実装と大差ないので，`stopWatch`ではなくテストの実行時間を渡すようにしましょう

2020-12-10 13:11 UTC, ty-v1 commented on src/main/java/jp/kusumotolab/kgenprog/KGenProgMain.java
> +      return format.format(
全部NaN(=全部の個体がテスト実行できなかった)ときの処理を追加してください

2020-12-10 13:11 UTC, ty-v1 commented on src/main/java/jp/kusumotolab/kgenprog/KGenProgMain.java
> +          getSumTestTime(variants),
ここなおっていないので修正お願いします

2020-12-18 04:31 UTC, ty-v1 requested changes
レビューしました

2020-12-18 04:31 UTC, ty-v1 commented on src/main/java/jp/kusumotolab/kgenprog/project/test/TestResults.java
> +  private double testTime;
final

2020-12-18 04:31 UTC, ty-v1 commented on src/main/java/jp/kusumotolab/kgenprog/project/test/TestThread.java
> +      final CoverageMeasurementListener listener = new CoverageMeasurementListener();
具象クラスでなく抽象クラスにしましょう

2020-12-18 04:34 UTC, ty-v1 requested changes

2020-12-18 04:34 UTC, ty-v1 commented on src/main/java/jp/kusumotolab/kgenprog/KGenProgMain.java
> +      final var max = variants.stream()
ここだけ`var`を使っているのは気持ち悪いので，`var`を外しましょう

2020-12-18 04:34 UTC, ty-v1 commented on src/main/java/jp/kusumotolab/kgenprog/KGenProgMain.java
> +      final var min = variants.stream()
同様

2020-12-28 07:49 UTC, ty-v1 requested changes
レビューしました

2020-12-28 07:49 UTC, ty-v1 commented on src/main/java/jp/kusumotolab/kgenprog/project/test/TestResults.java
> +    this.testTime = Double.NaN;
`testExecTime`のほうがいいと思います

2021-01-14 07:46 UTC, ty-v1 requested changes
レビューしました

2021-01-14 07:46 UTC, ty-v1 commented on src/main/java/jp/kusumotolab/kgenprog/KGenProgMain.java
> +          .filter(e -> Double.compare(e, Double.NaN) != 0)
`Double#isNaN`を使いましょう

2021-01-14 07:46 UTC, ty-v1 commented on src/main/java/jp/kusumotolab/kgenprog/KGenProgMain.java
> +          .filter(e -> Double.compare(e, Double.NaN) != 0)
`Double#isNaN`を使いましょう

2021-01-14 07:46 UTC, ty-v1 commented on src/main/java/jp/kusumotolab/kgenprog/KGenProgMain.java
> +              .filter(e -> Double.compare(e, Double.NaN) != 0)
`Double#isNaN`を使いましょう

2021-01-15 09:36 UTC, ty-v1 approved these changes
LGTMです．　　
お疲れさまです

2021-01-15 09:36 UTC, merged