ConfigurationBuilderTestの実装を改善
kusumotolab/kGenProg pull request #817
Opened 2020-12-08 06:07 UTC by shinsuke-mat

resolve #655
resolve #805

#807 から直接ブランチを生やしているので注意．
ファイル差分に #807 が含まれます．

#807 マージ後にこのブランチにmasterを再マージするので，その後reviewしてください．

### やったこと（本質）
- `ConfigurationBuilderTest` をリファクタリング
3053行 → 570行に削減
  - Configuration専用のカスタムアサートクラス `ConfigurationAssert` を作成
  - 全てのテストを「部分的にパラメタを書き換えてその部分をassert，それ以外をデフォルトと比較」とうい流れに変更
  - パラメタ変更を一つずつではなくまとめてテストするように変更

- オブジェクトのフィールドを再帰的に比較するために，assertjのバージョンを更新（3.10 → 3.18）
  - 新API `usingRecursiveComparison()` が使える

### やったこと（バグ修正）
- symlink警告周りのバグ．toml読み込み時のみしかsymlink警告がでなかった部分を修正

### やったこと（伴う細かい修正）
- stdout周りのテストを改善
- immutablelist.of → list.of
- リフレクション時の余計な可視性変更を削除
- シンボリックリンクテストの環境依存問題を回避 #805
完全解決ではなくsymlink生成時に即座にテストをやめるように変更

2020-12-08 06:08 UTC, shinsuke-mat commented
@hrtwt 君のwin環境でこのブランチのテストが通るかだけ確認してもらえますか．
コードのレビューは不要です．@hnymA に依頼してます．

2020-12-08 06:58 UTC, hrtwt approved these changes
ignore なテスト以外の全テストに通過しました

2020-12-08 09:30 UTC, shinsuke-mat commented
@hnymA 
#807 マージされたのでreviewお願いします

2020-12-09 07:02 UTC, hnymA requested changes
コメント・質問しました．
typoなど簡単な修正はこちらでpushしました

2020-12-10 00:08 UTC, shinsuke-mat commented on src/test/java/jp/kusumotolab/kgenprog/ConfigurationBuilderTest.java
> +  private final List<Path> productPaths = List.of(productPath);
機能は全く同じ．どちらもimmutable & thread-safe & memory sufficient．

`ImmutableList.of` がguavaのAPIであるのに対し，`List.of` はJava9で導入されたAPI．
https://www.linkedin.com/pulse/list-creation-java-11-rizwan-ullah?articleId=6677884690617171968

後者の方がlib依存が少ない．

2020-12-10 00:45 UTC, shinsuke-mat commented on src/main/java/jp/kusumotolab/kgenprog/Configuration.java
> +          //field.setAccessible(true);
リフレクション対象クラスが `this` なので可視性の強制変更がいらない．
現状はいらないけど，別クラスに切り出されたりすると必要．
共起関係が強いので，削除するよりコメントアウトが良いと判断した．

コメントアウトの理由を書いといた．

2020-12-14 09:24 UTC, hnymA approved these changes

2020-12-14 09:24 UTC, merged

2020-12-14 09:24 UTC, hnymA commented
マージしました！お疲れ様です